# Site
repository: salmansamkhan.github.io
favicon: images/favicon.ico

# Personal info
name: Pathan Salmankhan
title: Senior PHP Developer
email: mailuser0011@gmail.com
website: bitbyteinfo.com/

# Social links
twitter_username: salmansamkhan
github_username:  salmansamkhan
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: salmansamkhan
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Pathan Salmankhan and I'm a senior PHP Developer. I have experience of making software, web apps, API's. I have worked at a number of projects gaining teamwork and leadership skills.

  I am most skilled in: <mark>PHP</mark> , <mark>Laravel</mark> , <mark>Codeigniter</mark> , <mark>AWS</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Cricket
   - Reading Books

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
