# Site settings
title: Salmankhan PHP Developer
twitter_username: salmansamkhan
name: Salmankhan

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/salmansamkhan
   
#Any buzzword skills you want to include
skills:
 - Laravel
 - PHP MVC
 

#Work experience is required
roles:
 - title: PHP Developer
   start: 2017
   end: 2018
   employer: Maahi IT
   description: IT Company
   
#Education is required
education:
 - level: Bachelor of Computer Application ( B.C.A )
   date: 2012-2015
   subject: Computer Science
   university: Maharaja Sayajirao University
   
 - level: Master of Computer Application ( M.C.A )
   date: 2015-2017
   subject: Computer Science
   university: Sardar Patel University

theme: jekyll-theme-cayman